// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SGE.Persistence.Contexts;

#nullable disable

namespace SGE.Persistence.Migrations;

[DbContext(typeof(SgeDbContext))]
[Migration("20260918133814_SeedStructuralCompany")]
partial class SeedStructuralCompany
{
}
